 <?php
// module/Companies/view/companies/companies/index.phtml:

 $title = 'Edit Company';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'companies',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('idcompanie'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('id')); // idusuario
 echo $this->formRow($form->get('address'));
 echo $this->formRow($form->get('phone'));
 echo $this->formRow($form->get('email'));
 echo $this->formRow($form->get('cities_idcity'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();